In [4]:
import pandas as pd
import numpy as np
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [5]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

## 01. Pandas version

In [6]:
pd.__version__

'3.0.6'

## 02. Record count

In [7]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

## 03 Fuel types

In [8]:
df.fuel_type.unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

## 04. Missing values

In [9]:
empty_col = df.isnull().any().sum()
empty_col

np.int64(2)

## 05. Fuel efficiency Asia

In [10]:
asia = df[(df['origin'] == 'Asia')]

In [11]:
asia.fuel_efficiency_mpg.max()

np.float64(41.2)

## 06. Median value of horsepower

In [12]:
median = df.horsepower.median()

In [13]:
median

np.float64(254.0)

In [14]:
mode = df['horsepower'].mode()[0]

In [15]:
mode

np.float64(252.0)

In [16]:
ll = df['horsepower'] = df['horsepower'].fillna(mode)

In [17]:
ll.median

<bound method Series.median of 0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64>

## 07 Sum of weights

In [18]:
asia_set = df[(df['origin'] == 'Asia')][['vehicle_weight','model_year']]
asia_set

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [19]:
asia_weight_year = asia_set[['vehicle_weight', 'model_year']]
X = asia_set.head(7).to_numpy()
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [20]:
X_transposed = X.T
X_transposed

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [21]:
X_transposed.shape

(2, 7)

In [22]:
XTX = np.dot(X, X_transposed)
XTX

array([[21961616, 22250432, 21921212, 22688888, 20753972, 24173916,
        22897924],
       [22250432, 22544164, 22209324, 22990376, 21022444, 24498332,
        23201348],
       [21921212, 22209324, 21880909, 22646666, 20716479, 24128437,
        22855443],
       [22688888, 22990376, 22646666, 23448884, 21428846, 24992538,
        23662582],
       [20753972, 21022444, 20716479, 21428846, 19630549, 22818647,
        21629633],
       [24173916, 24498332, 24128437, 24992538, 22818647, 26646941,
        25217899],
       [22897924, 23201348, 22855443, 23662582, 21629633, 25217899,
        23878861]])

In [23]:
XTX.shape

(7, 7)

In [27]:
XTX_invert = np.linalg.pinv(XTX)
XTX_invert

array([[ 4.38279333e-07,  6.97066123e-08,  4.95291129e-07,
        -5.87932998e-07,  1.90856231e-06, -1.69640601e-06,
        -3.11490552e-07],
       [ 6.97066123e-08,  1.17141786e-08,  7.86771771e-08,
        -9.17635542e-08,  3.01043872e-07, -2.66153687e-07,
        -4.82529561e-08],
       [ 4.95291129e-07,  7.86771771e-08,  5.59734047e-07,
        -6.64681393e-07,  2.15721691e-06, -1.91764036e-06,
        -3.52208541e-07],
       [-5.87932998e-07, -9.17635542e-08, -6.64681393e-07,
         7.93538112e-07, -2.56722053e-06,  2.28581234e-06,
         4.21433252e-07],
       [ 1.90856231e-06,  3.01043872e-07,  2.15721691e-06,
        -2.56722053e-06,  8.32116310e-06, -7.40187337e-06,
        -1.36158227e-06],
       [-1.69640601e-06, -2.66153687e-07, -1.91764036e-06,
         2.28581234e-06, -7.40187337e-06,  6.58737961e-06,
         1.21315592e-06],
       [-3.11490552e-07, -4.82529561e-08, -3.52208541e-07,
         4.21433252e-07, -1.36158227e-06,  1.21315592e-06,
         2.24025075e-07]])

In [28]:
XTX_invert.shape

(7, 7)

In [30]:
a = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
a.shape

(7,)

In [35]:
X_transpose_XTX_invert = np.dot(X_transposed, XTX_invert)
w = np.dot (X_transpose_XTX_invert, a)
w
w.shape

(2,)

In [37]:
sum_w=np.sum(w)
sum_w

np.float64(0.3691969690492478)